name: "Haskell"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-22.04
  
    strategy:
      matrix:
        stack_yaml:
          - stack.yaml
          - stack-lts-19.33.yaml
          - stack-lts-20.26.yaml
          - stack-lts-21.25.yaml
          - stack-lts-22.43.yaml
          - stack-lts-23.19.yaml
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix-shell --run "stack test --stack-yaml ${{ matrix.stack_yaml }}"
